// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package proto;

/**
 * Protobuf type {@code OrderRespone}
 */
public final class OrderRespone extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:OrderRespone)
        OrderResponeOrBuilder {
    // Use OrderRespone.newBuilder() to construct.
    private OrderRespone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private OrderRespone() {
        orderId_ = 0;
        price_ = 0;
        name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private OrderRespone(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        orderId_ = input.readInt32();
                        break;
                    }
                    case 16: {

                        price_ = input.readInt32();
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        name_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Order.internal_static_OrderRespone_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Order.internal_static_OrderRespone_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        OrderRespone.class, Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private int orderId_;

    /**
     * <code>int32 orderId = 1;</code>
     */
    public int getOrderId() {
        return orderId_;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private int price_;

    /**
     * <code>int32 price = 2;</code>
     */
    public int getPrice() {
        return price_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;

    /**
     * <code>string name = 3;</code>
     */
    public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (orderId_ != 0) {
            output.writeInt32(1, orderId_);
        }
        if (price_ != 0) {
            output.writeInt32(2, price_);
        }
        if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (orderId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, orderId_);
        }
        if (price_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, price_);
        }
        if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof OrderRespone)) {
            return super.equals(obj);
        }
        OrderRespone other = (OrderRespone) obj;

        boolean result = true;
        result = result && (getOrderId()
                == other.getOrderId());
        result = result && (getPrice()
                == other.getPrice());
        result = result && getName()
                .equals(other.getName());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ORDERID_FIELD_NUMBER;
        hash = (53 * hash) + getOrderId();
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + getPrice();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static OrderRespone parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static OrderRespone parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static OrderRespone parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static OrderRespone parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static OrderRespone parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static OrderRespone parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static OrderRespone parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static OrderRespone parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static OrderRespone parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static OrderRespone parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static OrderRespone parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static OrderRespone parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(OrderRespone prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code OrderRespone}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:OrderRespone)
            OrderResponeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Order.internal_static_OrderRespone_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Order.internal_static_OrderRespone_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            OrderRespone.class, Builder.class);
        }

        // Construct using proto.OrderRespone.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            orderId_ = 0;

            price_ = 0;

            name_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Order.internal_static_OrderRespone_descriptor;
        }

        public OrderRespone getDefaultInstanceForType() {
            return OrderRespone.getDefaultInstance();
        }

        public OrderRespone build() {
            OrderRespone result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public OrderRespone buildPartial() {
            OrderRespone result = new OrderRespone(this);
            result.orderId_ = orderId_;
            result.price_ = price_;
            result.name_ = name_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof OrderRespone) {
                return mergeFrom((OrderRespone) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(OrderRespone other) {
            if (other == OrderRespone.getDefaultInstance()) return this;
            if (other.getOrderId() != 0) {
                setOrderId(other.getOrderId());
            }
            if (other.getPrice() != 0) {
                setPrice(other.getPrice());
            }
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                onChanged();
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            OrderRespone parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (OrderRespone) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int orderId_;

        /**
         * <code>int32 orderId = 1;</code>
         */
        public int getOrderId() {
            return orderId_;
        }

        /**
         * <code>int32 orderId = 1;</code>
         */
        public Builder setOrderId(int value) {

            orderId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 orderId = 1;</code>
         */
        public Builder clearOrderId() {

            orderId_ = 0;
            onChanged();
            return this;
        }

        private int price_;

        /**
         * <code>int32 price = 2;</code>
         */
        public int getPrice() {
            return price_;
        }

        /**
         * <code>int32 price = 2;</code>
         */
        public Builder setPrice(int value) {

            price_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 price = 2;</code>
         */
        public Builder clearPrice() {

            price_ = 0;
            onChanged();
            return this;
        }

        private Object name_ = "";

        /**
         * <code>string name = 3;</code>
         */
        public String getName() {
            Object ref = name_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 3;</code>
         */
        public Builder setName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 3;</code>
         */
        public Builder clearName() {

            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        /**
         * <code>string name = 3;</code>
         */
        public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            name_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:OrderRespone)
    }

    // @@protoc_insertion_point(class_scope:OrderRespone)
    private static final OrderRespone DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new OrderRespone();
    }

    public static OrderRespone getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderRespone>
            PARSER = new com.google.protobuf.AbstractParser<OrderRespone>() {
        public OrderRespone parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new OrderRespone(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<OrderRespone> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OrderRespone> getParserForType() {
        return PARSER;
    }

    public OrderRespone getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

