// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package proto;

public final class Order {
    private Order() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_OrderRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_OrderRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_OrderRespone_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_OrderRespone_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\013order.proto\"\037\n\014OrderRequest\022\017\n\007orderId" +
                        "\030\001 \001(\005\"<\n\014OrderRespone\022\017\n\007orderId\030\001 \001(\005\022" +
                        "\r\n\005price\030\002 \001(\005\022\014\n\004name\030\003 \001(\t28\n\014OrderSer" +
                        "vice\022(\n\010getOrder\022\r.OrderRequest\032\r.OrderR" +
                        "esponeB\t\n\005protoP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_OrderRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_OrderRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_OrderRequest_descriptor,
                new String[]{"OrderId",});
        internal_static_OrderRespone_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_OrderRespone_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_OrderRespone_descriptor,
                new String[]{"OrderId", "Price", "Name",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
