// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package proto;

public interface OrderRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:OrderRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 orderId = 1;</code>
     */
    int getOrderId();
}
