// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package proto;

public interface OrderResponeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:OrderRespone)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 orderId = 1;</code>
     */
    int getOrderId();

    /**
     * <code>int32 price = 2;</code>
     */
    int getPrice();

    /**
     * <code>string name = 3;</code>
     */
    String getName();

    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
