server:
  port: 14001
app:
  id: apollo-test
apollo:
  meta: http://127.0.0.1:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: dev,application
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: password
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ynwrkj.entity

