server:
  port: 14001
app:
  id: apollo-test
apollo:
  meta: http://127.0.0.1:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: dev,application
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ynwrkj.entity

